homepage: "https://github.com/IPPD-Testing-Suite/simdjson"
language: c++
primary_contact: "pauldreikossfuzz@gmail.com"
auto_ccs:
 - "lemire@gmail.com"
sanitizers:
- address
- undefined
main_repo: 'https://github.com/IPPD-Testing-Suite/simdjson.git'

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

