base_os_version: ubuntu-24-04
homepage: "https://www.aleksey.com/xmlsec/"
language: c++
primary_contact: "aleksey@aleksey.com"
auto_ccs:
  - "alekseysanin@gmail.com"
sanitizers:
  - address
  - undefined
main_repo: 'https://github.com/IPPD-Testing-Suite/xmlsec.git'

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

