homepage: "https://github.com/IPPD-Testing-Suite/fmt"
language: c++
primary_contact: "pauldreikossfuzz@gmail.com"
auto_ccs:
 - "victor.zverovich@gmail.com"
main_repo: 'https://github.com/IPPD-Testing-Suite/fmt.git'
