homepage: "https://github.com/IPPD-Testing-Suite/WavPack" 
language: c++
primary_contact: "david@wavpack.com" 
auto_ccs:
- dvbryant@gmail.com
- thuanpv.nus@gmail.com
sanitizers: 
- address 
- memory
- undefined
main_repo: https://github.com/IPPD-Testing-Suite/WavPack.git'

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

