homepage: "https://github.com/IPPD-Testing-Suite/ArduinoJson"
language: c++
primary_contact: "benoit.blanchon@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/IPPD-Testing-Suite/ArduinoJson.git'
